"""
Aero Language — Lexer (auto-generated by engine/generator.py)
==============================================================

DO NOT EDIT THIS FILE MANUALLY. It is regenerated deterministically
from config/language_spec.json by the spec-driven compiler-compiler.
"""

import enum
from typing import List


class TokenType(enum.Enum):
    KEYWORD = 1
    IDENTIFIER = 2
    INT_LITERAL = 3
    FLOAT_LITERAL = 4
    STRING_LITERAL = 5
    BOOL_LITERAL = 6
    OPERATOR = 7
    PUNCTUATION = 8
    EOF = 9


class LexerError(Exception):
    def __init__(self, position, message="Unexpected token structure"):
        self.position = position
        self.message = message
        super().__init__(f"LexerError at line {position[0]} column {position[1]}: {message}")


class Token:
    def __init__(self, type: TokenType, value: str, line: int, column: int):
        self.type = type
        self.value = value
        self.line = line
        self.column = column

# ── Language Tables (generated from config/language_spec.json by aero_sdk.optimizer.generator) ──
_KEYWORDS = {'let', 'fn', 'return', 'else', 'if', 'while'}
_BOOLEANS = {'true', 'false'}
_OPERATORS = ['&&', '>=', '==', '<=', '!=', '||', '=', '+', '*', '%', '>', '-', '/', '!', '<']
_PUNCTUATION = {'(', ')', '{', '}', ',', ';'}
_CUSTOM_ERRORS = {'@': "Unexpected character '@' - not a valid token", '#': "Unexpected character '#' - not a valid token", '$': "Unexpected character '$' - not a valid token", '~': "Unexpected character '~' - not a valid token", '`': "Unexpected character '`' - not a valid token"}


class Lexer:
    def __init__(self, source: str):
        self.source = source
        self.position = 0
        self.line = 1
        self.column = 1
        self.length = len(source)

    def tokenize(self) -> List[Token]:
        tokens = []

        while self.position < self.length:
            char = self.source[self.position]

            # 1. Whitespace
            if char == '\n':
                self.line += 1
                self.column = 1
                self.position += 1
                continue
            if char.isspace():
                self.column += 1
                self.position += 1
                continue

            # 2. Line comments (//)
            if char == '/' and self.position + 1 < self.length and self.source[self.position + 1] == '/':
                while self.position < self.length and self.source[self.position] != '\n':
                    self.position += 1
                continue

            # 3. Block comments (/* */)
            if char == '/' and self.position + 1 < self.length and self.source[self.position + 1] == '*':
                self.position += 2
                self.column += 2
                while self.position + 1 < self.length and not (self.source[self.position] == '*' and self.source[self.position + 1] == '/'):
                    if self.source[self.position] == '\n':
                        self.line += 1
                        self.column = 1
                    else:
                        self.column += 1
                    self.position += 1
                self.position += 2
                self.column += 2
                continue

            # 4. String literals
            if char in ('"', "'"):
                quote_type = char
                start_line, start_col = self.line, self.column
                value_chars = []
                self.position += 1
                self.column += 1
                while self.position < self.length and self.source[self.position] != quote_type:
                    curr_ch = self.source[self.position]
                    if curr_ch == '\n':
                        self.line += 1
                        self.column = 1
                    else:
                        self.column += 1
                    value_chars.append(curr_ch)
                    self.position += 1
                if self.position >= self.length:
                    raise LexerError((start_line, start_col), "Unterminated string literal")
                self.position += 1
                self.column += 1
                tokens.append(Token(TokenType.STRING_LITERAL, "".join(value_chars), start_line, start_col))
                continue

            # 5. Numeric literals
            if char.isdigit() or (char == '.' and self.position + 1 < self.length and self.source[self.position + 1].isdigit()):
                start_col = self.column
                num_chars = []
                has_dot = False
                if char == '.':
                    has_dot = True
                    num_chars.append('.')
                    self.position += 1
                    self.column += 1
                while self.position < self.length and (self.source[self.position].isdigit() or self.source[self.position] == '.'):
                    curr_ch = self.source[self.position]
                    if curr_ch == '.':
                        if has_dot:
                            break
                        has_dot = True
                    num_chars.append(curr_ch)
                    self.position += 1
                    self.column += 1
                num_str = "".join(num_chars)
                token_type = TokenType.FLOAT_LITERAL if has_dot else TokenType.INT_LITERAL
                tokens.append(Token(token_type, num_str, self.line, start_col))
                continue

            # 6. Operators (sorted by descending length)
            op_matched = False
            for op in _OPERATORS:
                op_len = len(op)
                if self.position + op_len <= self.length and self.source[self.position:self.position + op_len] == op:
                    tokens.append(Token(TokenType.OPERATOR, op, self.line, self.column))
                    self.position += op_len
                    self.column += op_len
                    op_matched = True
                    break
            if op_matched:
                continue

            # 7. Punctuation
            if char in _PUNCTUATION:
                tokens.append(Token(TokenType.PUNCTUATION, char, self.line, self.column))
                self.position += 1
                self.column += 1
                continue

            # 8. Keywords, booleans, identifiers
            if char.isalpha() or char == '_':
                start_col = self.column
                word_chars = [char]
                self.position += 1
                self.column += 1
                while self.position < self.length and (self.source[self.position].isalnum() or self.source[self.position] == '_'):
                    word_chars.append(self.source[self.position])
                    self.position += 1
                    self.column += 1
                word_str = "".join(word_chars)
                if word_str in _KEYWORDS:
                    tokens.append(Token(TokenType.KEYWORD, word_str, self.line, start_col))
                elif word_str in _BOOLEANS:
                    tokens.append(Token(TokenType.BOOL_LITERAL, word_str, self.line, start_col))
                else:
                    tokens.append(Token(TokenType.IDENTIFIER, word_str, self.line, start_col))
                continue

            # 9. Custom error characters
            if char in _CUSTOM_ERRORS:
                raise LexerError((self.line, self.column), _CUSTOM_ERRORS[char])

            raise LexerError((self.line, self.column), f"Unexpected character: {char}")

        tokens.append(Token(TokenType.EOF, "", self.line, self.column))
        return tokens


def tokenize(source: str) -> List[Token]:
    return Lexer(source).tokenize()
